name: CI

on:
  push:
    branches: [succinct]
  pull_request:
    branches: [succinct]
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            triple: aarch64-apple-darwin
          - os: ubuntu-22.04
            triple: x86_64-unknown-linux-gnu
          - os: buildjet-32vcpu-ubuntu-2204-arm
            triple: aarch64-unknown-linux-gnu
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install nightly toolchain
        id: rustc-toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2024-01-25
          default: true

      - uses: lukka/get-cmake@v3.27.4

      - name: Check out succinctlabs/rust
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          path: rust
          fetch-depth: 0

      - name: Check out succinctlabs/sp1
        uses: actions/checkout@v3
        with:
          repository: succinctlabs/sp1
          ref: main
          path: sp1

      - name: Build
        run: GITHUB_ACTIONS=false SP1_BUILD_DIR=$GITHUB_WORKSPACE cargo run --bin cargo-prove -- prove build-toolchain
        working-directory: sp1

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: rust-toolchain-${{ matrix.triple }}
          path: |
            rust/build/${{ matrix.triple }}/stage2
            !rust/build/${{ matrix.triple }}/stage2/lib/rustlib/src
            !rust/build/${{ matrix.triple }}/stage2/lib/rustlib/rustc-src
